### ISSUE TITLE
View meeting info

### ISSUE THREAD

**Issue by devsgarage** [devsgarage/tulsa-dnug-website#4]
- street address
- meeting date/time
- meeting agenda (broken out by time)
     - 6-6:20pm       Meet, Greet & Eat
     - 6:20-6:30pm  Announcements and speaker introduction
     - 6:30-7:15pm Lightening talk
     - 7:15-8:30pm Main presentation
     - 8:30pm Prize drawing
- After meeting snacks and drinks at nearby pub

**Comment by jeff4intellacore** [comment]
Again, do you want to integrate with meetup for new meeting announcements?

**Comment by devsgarage** [comment]
If we can get this information from meetup, lets do it!
